config/routes.rb
Rails.application.routes.draw do
  root 'top#main'
  get 'top/main'
  resources :products, only: [:index, :new, :create, :destroy]
  resources :cart_items, only: [:create, :destroy]
  resources :carts, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    has_one :product
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :cart_item, dependent: :destroy, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_cart
        if session[:cart_id]
            cart = Cart.find_by(id: session[:cart_id])
            if cart.nil? then
                cart = Cart.create
                session[:cart_id] = cart.id
            end
        else
            cart = Cart.create
            session[:cart_id] = cart.id
        end
        
        cart
    end
    helper_method :current_cartend

    def getItemCounts
        cart = current_cart
        return cart.cart_items.count
    end
    helper_method :getItemCounts
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    def create
        items = params[:cart_item]
        pid = items[:product_id]
        qty = items[:qty].to_i
    
        if qty <= 0 then
            redirect_to top_main_path
        else
    
          cart = current_cart
          cart_i =  CartItem.new(
            qty: qty,
            product_id: pid
          )
          
          cart.cart_items << cart_i
      
          flash[:name] = Product.find(pid).name
          flash[:qty] = qty
      
          redirect_to top_main_path
        end
    end

    def destroy
        id = params[:id]
        current_cart.cart_items.find(id).destroy
    
        redirect_to carts_path
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def index
        @cart_items = current_cart.cart_items
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @pdts = Product.all
  end

  def new
    @p = Product.new
  end
  
  def create
    p = params[:product]
    @pd = Product.new(
      name: p[:name],
      price: p[:price].to_i
    )
    
    @pd.save
    p @pd.errors.full_messages
    
    redirect_to products_path
  end

  def destroy
    id = params[:id]
    Product.find(id).destroy
    redirect_to products_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    @products = Product.all
    @item = CartItem.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/index.html.erb
<%= link_to '戻る', top_main_path %>
<hr />
<% psum = 0 %>
<% @cart_items.each do |item| %>
    <% product = Product.find_by(id: item.product_id) %>
    <% if product.nil? then %>
        <% next %>
    <% end %>
    <div>
        <div>
            <%= product.name%>
            <%= product.price %>円
        </div>
        <div>
            個数: <%= item.qty %>
        </div>
        <div>
            計 <%= item.qty * product.price %>円
        </div>
        <div class="link">
            <%= link_to 'カートから削除する', cart_item_path(item.id), method: :delete %>
        </div>
    </div>
    <br />
    <% psum = psum + item.qty * product.price %>
<% end %>
<hr />
合計 <%= psum %>円

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L71</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>商品一覧</h1>
<hr/>

<% @pdts.each do |p| %>
    <%= p.name%> <%= p.price %>円
    
    <%= link_to '削除', product_path(p.id), method: :delete %>
    
   <hr/>
<% end %>

<%= link_to '新しい商品を追加', new_product_path %>
<%= link_to '戻る', top_main_path %>

app/views/products/new.html.erb
<%= link_to '戻る', products_path %>
<%= form_for @p, url: {action: :create} do |pd| %>
    <%= pd.label :name, '商品名'%>
    <%= pd.text_field :name %>
    <br />
    <%= pd.label :price, '値段' %>
    <%= pd.number_field :price, min: "0", value: "0"%>
    <%= pd.submit '登録' %>
<% end %>

app/views/top/main.html.erb
<h1>ショップ</h1>

<% if flash[:name] then %>
    <% name = flash[:name] %>
    <% qty = flash[:qty] %>
    <% m = "#{name} を #{qty}個、カートに追加しました。" %>
    
    <%= javascript_tag do %>
        sendMessage("<%= m %>");
    <% end %>
<% end %>

<div class="link">
    <%= link_to '商品管理', products_path %>
</div>

<div class="link">
    <%= link_to 'カートの中を見る', carts_path %>
</div>
<hr />
<div id="list">
    <% @products.each do |p| %>
        <% pid = p.id %>
        <div class="card">
            <%= form_for @item, url: {controller: 'cart_items', action: :create} do |c| %>
                <div class="name">
                    <%= p.name %>
                </div>
                <div class="price">
                    <%= p.price %>円
                </div>
                <div class="form">
                    <%= c.hidden_field :product_id, value: pid %>
                    <%= c.label :qty, '数量' %>
                    <%= c.number_field :qty, min: "0", value: "0" %>
                    <%= c.submit 'カートに入れる' %>
                </div>
            <% end %>
        </div>
        <br />
    <% end %>
</div>